name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [24.x, 26.x]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@${{ matrix.node }}
          cache: true
      - name: Run test
        run: |
          pnpm install --frozen-lockfile
          pnpm test
